spring:
  application:
    name: dev-workbench
  profiles:
    active: dev
  jpa:
    hibernate:
      ddl-auto: update
  jackson:
    serialization:
      indent_output: true
      write_dates_as_timestamps: false
      write_durations_as_timestamps: false

devworkbench:
  jira:
    baseUri:  "https://myjira.de/browse"
